INSERT INTO user (username, password, status,first_name,last_name,gender,section,semester,academic_year,year,e_mail,faculty,department)
VALUES ('admin','admin','0','','','','','','',2557,'','','');



INSERT INTO brown_peterson_question (first_word, second_word, third_word, trigram_type, trigram_language) VALUES 
('lab','pencil','warrior','word','english'),
('swan','water','report','word','english'),
('tree','android','dolphin','word','english'),
('sword','cat','monitor','word','english'),
('code','elbow','mangosteen','word','english'),
('monitor','log','image','word','english'),
('exam','rabbit','keyboard','word','english'),
('log','laptop','router','word','english'),
('park','image','router','word','english'),
('graph','android','keyboard','word','english'),
('circle','swan','address','word','english'),
('pencil','paper','dolphin','word','english'),
('rabbit','report','log','word','english'),
('cat','circle','address','word','english'),
('exam','address','wheel','word','english'),
('rabbit','tree','monitor','word','english'),
('wheel','park','router','word','english'),
('android','paper','address','word','english'),
('mangosteen','pencil','cat','word','english'),
('letter','lab','pencil','word','english'),
('address','circle','laptop','word','english'),
('water','mangosteen','code','word','english'),
('android','park','warrior','word','english'),
('lab','wheel','router','word','english'),
('winter','rabbit','address','word','english'),
('monitor','android','log','word','english'),
('smile','router','paper','word','english'),
('leaf','wheel','teacher','word','english'),
('code','dolphin','pencil','word','english'),
('monkey','paper','mangosteen','word','english'),
('wheel','cake','router','word','english'),
('hand','rabbit','mangosteen','word','english'),
('router','hand','silver','word','english'),
('monitor','pencil','swan','word','english'),
('student','square','door','word','english'),
('bread','wheel','mangosteen','word','english'),
('circle','tree','address','word','english'),
('leaf','square','summer','word','english'),
('hand','cookie','winter','word','english'),
('teacher','android','lab','word','english'),
('swan','sword','label','word','english'),
('hand','smile','water','word','english'),
('cake','square','teacher','word','english'),
('code','pencil','report','word','english'),
('cake','finger','label','word','english'),
('leaf','silver','wheel','word','english'),
('pencil','router','door','word','english'),
('silver','graph','circle','word','english'),
('finger','silver','leaf','word','english'),
('image','silver','cat','word','english'),
('code','elbow','student','word','english'),
('graph','finger','address','word','english'),
('wheel','router','bread','word','english'),
('warrior','log','elbow','word','english'),
('silver','elbow','cake','word','english'),
('android','summer','paper','word','english'),
('finger','cake','report','word','english'),
('rabbit','report','swan','word','english'),
('leaf','elbow','report','word','english'),
('lab','image','teacher','word','english'),
('cookie','cake','silver','word','english'),
('letter','water','circle','word','english'),
('label','paper','finger','word','english'),
('cake','wheel','label','word','english'),
('image','graph','address','word','english'),
('keyboard','circle','bread','word','english'),
('monkey','leaf','mangosteen','word','english'),
('monitor','code','pencil','word','english'),
('cake','water','silver','word','english'),
('text','elbow','router','word','english'),
('tree','finger','silver','word','english'),
('paper','blue','wheel','word','english'),
('elbow','text','winter','word','english'),
('cookie','blue','silver','word','english'),
('finger','dolphin','leaf','word','english'),
('wheel','yellow','school','word','english'),
('address','sword','cat','word','english'),
('android','teacher','code','word','english'),
('student','finger','leaf','word','english'),
('report','circle','lab','word','english'),
('yellow','park','student','word','english'),
('address','rabbit','paper','word','english'),
('leaf','router','smile','word','english'),
('graph','dolphin','smile','word','english'),
('square','report','tree','word','english'),
('finger','letter','bread','word','english'),
('winter','android','bread','word','english'),
('mangosteen','blue','rabbit','word','english'),
('paper','teacher','wheel','word','english'),
('pencil','water','graph','word','english'),
('warrior','leaf','monkey','word','english'),
('router','graph','smile','word','english'),
('hand','smile','monitor','word','english'),
('code','image','silver','word','english'),
('elbow','park','router','word','english'),
('sword','leaf','student','word','english'),
('dolphin','paper','wheel','word','english'),
('laptop','cake','summer','word','english'),
('circle','school','white','word','english'),
('asd','gbh','mki','nonsense','english'),
('ฟหก',' สนย',' ยวส','nonsense','thai'),
('กดพ',' ปฟห',' ยนร','nonsense','thai'),
('﻿ดวง','พยาบาล','อนุรักษ์','word','thai'),
('กลม','ราชการ','โทรทัศน์','word','thai'),
('ขนม','อากาศ','นวัตกรรม','word','thai'),
('ครก','รายการ','มนุษย์','word','thai'),
('สระ','ดาวเทียม','พลเรือน','word','thai'),
('มติ','กว้างขวาง','องค์กร','word','thai'),
('ความ','การเมือง','ยุติธรรม','word','thai'),
('ผอม','สถิติ','เครือข่าย','word','thai'),
('ฟอก','ผลงาน','สถาปัตย์','word','thai'),
('ภาพ','รถเมล์','ลิขสิทธิ์','word','thai'),
('กลาง','ประกวด','วิศวกร','word','thai'),
('ผล','ดนตรี','หลักฐาน','word','thai'),
('ช้าง','มะม่วง','รถยนต์','word','thai'),
('ภาค','ความรู้','ปรากฏ','word','thai'),
('สนาม','หนังสือ','นโยบาย','word','thai'),
('ฉลอง','ซุกซ่อน','วิเคราะห์','word','thai'),
('ใหญ่','เสมือน','เผ่าพันธุ์','word','thai'),
('เสริม','ตกลง','รัฐศาสตร์','word','thai'),
('สนุก','คุณค่า','ศิลปกรรม','word','thai'),
('สนิม','เอกสาร','สัมพันธ์','word','thai'),
('อนุรักษ์','ดาวเทียม','ฉลอง','word','thai'),
('โทรทัศน์','กว้างขวาง','ใหญ่','word','thai'),
('นวัตกรรม','การเมือง','เสริม','word','thai'),
('มนุษย์','สถิติ','สนุก','word','thai'),
('พลเรือน','ผลงาน','สนิม','word','thai'),
('องค์กร','รถเมล์','ดวง','word','thai'),
('ยุติธรรม','ประกวด','กลม','word','thai'),
('เครือข่าย','ดนตรี','ขนม','word','thai'),
('สถาปัตย์','มะม่วง','ครก','word','thai'),
('ลิขสิทธิ์','ความรู้','สระ','word','thai'),
('วิศวกร','หนังสือ','มติ','word','thai'),
('หลักฐาน','พยาบาล','ความ','word','thai'),
('รถยนต์','ราชการ','ผอม','word','thai'),
('ปรากฏ','อากาศ','ฟอก','word','thai'),
('นโยบาย','รายการ','ภาพ','word','thai'),
('วิเคราะห์','ซุกซ่อน','กลาง','word','thai'),
('เผ่าพันธุ์','เสมือน','ผล','word','thai'),
('รัฐศาสตร์','ตกลง','ช้าง','word','thai'),
('ศิลปกรรม','คุณค่า','ภาค','word','thai'),
('สัมพันธ์','เอกสาร','สนาม','word','thai'),
('ซุกซ่อน','อนุรักษ์','มติ','word','thai'),
('เสมือน','โทรทัศน์','ความ','word','thai'),
('ตกลง','นวัตกรรม','ผอม','word','thai'),
('คุณค่า','มนุษย์','ฟอก','word','thai'),
('เอกสาร','พลเรือน','ภาพ','word','thai'),
('ประกวด','องค์กร','ฉลอง','word','thai'),
('ดนตรี','ยุติธรรม','ใหญ่','word','thai'),
('มะม่วง','เครือข่าย','เสริม','word','thai'),
('ความรู้','สถาปัตย์','สนุก','word','thai'),
('หนังสือ','ลิขสิทธิ์','สนิม','word','thai'),
('กว้างขวาง','วิศวกร','ดวง','word','thai'),
('การเมือง','หลักฐาน','กลม','word','thai'),
('สถิติ','รถยนต์','ขนม','word','thai'),
('ผลงาน','ปรากฏ','ครก','word','thai'),
('รถเมล์','นโยบาย','สระ','word','thai'),
('พยาบาล','วิเคราะห์','กลาง','word','thai'),
('ราชการ','เผ่าพันธุ์','ผล','word','thai'),
('อากาศ','รัฐศาสตร์','ช้าง','word','thai'),
('รายการ','ศิลปกรรม','ภาค','word','thai'),
('ดาวเทียม','สัมพันธ์','สนาม','word','thai'),
('﻿WRT','HGF','IKL','nonsense','english'),
('IML','GFD','PLR','nonsense','english'),
('NHT','FDS','QWE','nonsense','english'),
('FWQ','SPT','RTY','nonsense','english'),
('TYH','GRW','SGU','nonsense','english'),
('HNT','QWS','YPS','nonsense','english'),
('NMV','QSX','SDF','nonsense','english'),
('CDS','JXD','DFG','nonsense','english'),
('FGH','IJX','GHK','nonsense','english'),
('HJY','QBF','HJK','nonsense','english'),
('QWT','LKJ','VFR','nonsense','english'),
('FGB','ZXC','CDE','nonsense','english'),
('FNH','BCV','XSW','nonsense','english'),
('MLK','CVB','ZQA','nonsense','english'),
('YPT','BNM','WSX','nonsense','english'),
('WTY','MNB','EDC','nonsense','english'),
('GHJ','NBV','RFV','nonsense','english'),
('HJK','VCX','TGB','nonsense','english'),
('NJI','XZA','YHN','nonsense','english'),
('BGR','KJH','UJM','nonsense','english'),
('VFR','IKL','HGF','nonsense','english'),
('CDE','PLR','GFD','nonsense','english'),
('XSW','QWE','FDS','nonsense','english'),
('ZQA','RTY','SPT','nonsense','english'),
('WSX','TYU','TRW','nonsense','english'),
('EDC','YPS','QWS','nonsense','english'),
('RFV','SDF','QSX','nonsense','english'),
('TGB','DFG','JXD','nonsense','english'),
('YHN','GHK','IJX','nonsense','english'),
('UJM','HJK','QBF','nonsense','english'),
('IKL','VFR','WRT','nonsense','english'),
('PLR','CDE','IML','nonsense','english'),
('QWE','XSW','NHT','nonsense','english'),
('RTY','ZQA','FWQ','nonsense','english'),
('TYU','WSX','TYH','nonsense','english'),
('YPS','EDC','HNT','nonsense','english'),
('SDF','RFV','NMV','nonsense','english'),
('DFG','TGB','CDS','nonsense','english'),
('GHK','YHN','FGH','nonsense','english'),
('HJK','UJM','HJY','nonsense','english'),
('LKJ','QWT','VFR','nonsense','english'),
('ZXC','FGB','CDE','nonsense','english'),
('XCV','FNH','XSW','nonsense','english'),
('CVB','MLK','ZQA','nonsense','english'),
('BNM','YPT','WSX','nonsense','english'),
('MNB','WTY','EDC','nonsense','english'),
('NBV','GHJ','RFV','nonsense','english'),
('VCX','HJK','TGB','nonsense','english'),
('XZA','NJI','YHN','nonsense','english'),
('KJH','BGR','UJM','nonsense','english'),
('HGF','WRT','QWT','nonsense','english'),
('GFD','IML','FGB','nonsense','english'),
('FDS','NHT','FNH','nonsense','english'),
('SPT','FWQ','MLK','nonsense','english'),
('CRW','TYH','YPT','nonsense','english'),
('QWS','HNT','WTY','nonsense','english'),
('QSX','NMV','GHJ','nonsense','english'),
('JXD','CDS','HJK','nonsense','english'),
('IJX','FGH','NJI','nonsense','english'),
('QBF','HJY','BGR','nonsense','english'),
('﻿ชขจ','ฆซฉ','ษศข','nonsense','thai'),
('จตห','อธย','ซศธ','nonsense','thai'),
('จนย','บฒศ','กดฮ','nonsense','thai'),
('ฟกห','ฎฑส','ษกฆ','nonsense','thai'),
('ผปซ','วธฮ','พธษ','nonsense','thai'),
('สงฝ','ชบษ','ดกฆ','nonsense','thai'),
('สรข','ฏษร','นรฐ','nonsense','thai'),
('สยว','รษฮ','ซงฬ','nonsense','thai'),
('กหฟ','ฆฟน','ฑพก','nonsense','thai'),
('ดปห','ซยฑ','ฮคจ','nonsense','thai'),
('มทส','ขญณ','ฆซฉ','nonsense','thai'),
('ลบย','ศดห','อธย','nonsense','thai'),
('งยว','ฟฆก','บฒศ','nonsense','thai'),
('พฟห','ฉฮธ','ฎฑส','nonsense','thai'),
('ปฮผ','ญฐช','วธฮ','nonsense','thai'),
('ทฒส','ทมฆ','ชบษ','nonsense','thai'),
('ศนห','ฆกณ','ฏษร','nonsense','thai'),
('ฐบว','ยฐท','รษฮ','nonsense','thai'),
('พธผ','มฬฝ','ฆฟน','nonsense','thai'),
('สมข','งบธ','ซยฑ','nonsense','thai'),
('ฎฑธ','ษศข','ขญณ','nonsense','thai'),
('ฆฏณ','ซศธ','ศดห','nonsense','thai'),
('ฉฮศ','กดฮ','ฟฆก','nonsense','thai'),
('ซฐญ','ษกฆ','ฉฮธ','nonsense','thai'),
('ศซณ','พธษ','ญฐช','nonsense','thai'),
('ฆดว','ดกฆ','ทมฆ','nonsense','thai'),
('งดว','นรฐ','ฆกณ','nonsense','thai'),
('ฆฏฮ','ซงฬ','ยฐท','nonsense','thai'),
('จณษ','ฑพก','มฬฝ','nonsense','thai'),
('ซขฐ','ฮคจ','งบธ','nonsense','thai'),
('ษศข','ฎฑธ','มทส','nonsense','thai'),
('ซศธ','ฆฏณ','ลบย','nonsense','thai'),
('กดฮ','ฉฮศ','งยว','nonsense','thai'),
('ษกฆ','ซฐญ','พฟห','nonsense','thai'),
('พธษ','ศซณ','ปฮผ','nonsense','thai'),
('ดกฆ','ฆดว','ทฒส','nonsense','thai'),
('นรฐ','งดว','ศนห','nonsense','thai'),
('ซงฬ','ฆฏฮ','ฐบว','nonsense','thai'),
('ฑพก','จณษ','พธผ','nonsense','thai'),
('ฮคจ','ซขฐ','สมข','nonsense','thai'),
('ขญณ','มทส','ฎฑธ','nonsense','thai'),
('ศดห','ลบย','ฆฏณ','nonsense','thai'),
('ฟฆก','งยว','ฉฮศ','nonsense','thai'),
('ฉฮธ','พฟห','ซฐญ','nonsense','thai'),
('ญฐช','ปฮผ','ศซณ','nonsense','thai'),
('ทมฆ','ทฒส','ฆดว','nonsense','thai'),
('ฆกณ','ศนห','งดว','nonsense','thai'),
('ยฐท','ฐบว','ฆฏฮ','nonsense','thai'),
('มฬฝ','พธผ','จณษ','nonsense','thai'),
('งบธ','สมข','ซขฐ','nonsense','thai'),
('ฆซฉ','ชขจ','มทส','nonsense','thai'),
('อธย','จตห','ลบย','nonsense','thai'),
('บฒศ','จนย','งยว','nonsense','thai'),
('ฎฑส','ฟกห','พฟห','nonsense','thai'),
('วธฮ','ผปซ','ปฮผ','nonsense','thai'),
('ชบษ','สงฝ','ทฒส','nonsense','thai'),
('ฏษร','สรข','ศนห','nonsense','thai'),
('รษฮ','สยว','ฐบว','nonsense','thai'),
('ฆฟน','กหฟ','พธผ','nonsense','thai'),
('ซยฑ','ดปห','สมข','nonsense','thai');

INSERT INTO garner_interference_color (color_code, color, saturation) VALUES 
('E88C8C','red',1), 	('E37575','red',2), 	('DF5E5E','red',3), 	('DA4747','red',4), 	('D63030','red',5),
('D11919','red',6), 	('BC1616','red',7), 	('A71414','red',8), 	('921212','red',9), 	('7D0F0F','red',10),
('8099CC','blue',1), 	('6685C2','blue',2), 	('4D70B8','blue',3), 	('335CA3','blue',4), 	('1947A3','blue',5),
('003399','blue',6), 	('002E8A','blue',7), 	('00297A','blue',8), 	('00246B','blue',9), 	('001F5C','blue',10),
('FFE680','yellow',1),	('FFE066','yellow',2),	('FFDB4D','yellow',3), ('FFD633','yellow',4),	('FFD119','yellow',5), 
('FFCC00','yellow',6),	('E6B800','yellow',7),	('CCA300','yellow',8), ('B28F00','yellow',9),	('997A00','yellow',10), 
('B2FF99','green',1), 	('A3FF85','green',2), 	('94FF70','green',3), 	('85FF5C','green',4),	('75FF47','green',5), 
('66FF33','green',6), 	('5CE62E','green',7), 	('52CC29','green',8), 	('47B224','green',9),	('3D991F','green',10), 
('DCDCDC','grey',1), 	('D6D6D6','grey',2), 	('CFCFCF','grey',3), 	('C8C8C8','grey',4), 	('C1C1C1','grey',5), 
('BABABA','grey',6), 	('A7A7A7','grey',7), 	('959595','grey',8), 	('828282','grey',9), 	('707070','grey',10); 

INSERT INTO garner_interference_question (color_pic, size_pic, color_question, size_question, color_match, size_match) VALUES 
('dark' , 'big'  , 'dark' , 'big'  , 1, 1),
('dark' , 'big'  , 'dark' , 'small', 1, 0),
('dark' , 'big'  , 'light', 'big'  , 0, 1),
('dark' , 'big'  , 'light', 'small', 0, 0),
('dark' , 'small', 'dark' , 'big'  , 1, 0),
('dark' , 'small', 'dark' , 'small', 1, 1),
('dark' , 'small', 'light', 'big'  , 0, 0),
('dark' , 'small', 'light', 'small', 0, 1),
('light', 'big'  , 'dark' , 'big'  , 0, 1),
('light', 'big'  , 'dark' , 'small', 0, 0),
('light', 'big'  , 'light', 'big'  , 1, 1),
('light', 'big'  , 'light', 'small', 1, 0),
('light', 'small', 'dark' , 'big'  , 0, 0),
('light', 'small', 'dark' , 'small', 0, 1),
('light', 'small', 'light', 'big'  , 1, 0),
('light', 'small', 'light', 'small', 1, 1);

INSERT INTO simon_effect_question (color,alphabet,direction) VALUES
('red','O','up'),
('red','X','right'),
('green','O','left'),
('green','X','down');

INSERT INTO stroop_engword_question(color_word, ink_color, question_type) VALUES
('black','black',1),	('black','blue',1),	('black','red',1),	('black','green',1),	('black','purple',1),	('black','yellow',1),
('blue','black',1),	('blue','blue',1),	('blue','red',1),	('blue','green',1),	('blue','purple',1),	('blue','yellow',1),
('red','black',1),	('red','blue',1),	('red','red',1),	('red','green',1),	('red','purple',1),	('red','yellow',1),
('green','black',1),	('green','blue',1),	('green','red',1),	('green','green',1),	('green','purple',1),	('green','yellow',1),
('purple','black',1),	('purple','blue',1),	('purple','red',1),	('purple','green',1),	('purple','purple',1),	('purple','yellow',1),
('yellow','black',1),	('yellow','blue',1),	('yellow','red',1),	('yellow','green',1),	('yellow','purple',1),	('yellow','yellow',1),
('ดำ','black',0),	('ดำ','blue',0),	('ดำ','red',0),	('ดำ','green',0),	('ดำ','purple',0),	('ดำ','yellow',0),
('น้ำเงิน','black',0),	('น้ำเงิน','blue',0),	('น้ำเงิน','red',0),	('น้ำเงิน','green',0),	('น้ำเงิน','purple',0),	('น้ำเงิน','yellow',0),
('แดง','black',0),	('แดง','blue',0),	('แดง','red',0),	('แดง','green',0),	('แดง','purple',0),	('แดง','yellow',0),
('เขียว','black',0),	('เขียว','blue',0),	('เขียว','red',0),	('เขียว','green',0),	('เขียว','purple',0),	('เขียว','yellow',0),
('ม่วง','black',0),	('ม่วง','blue',0),	('ม่วง','red',0),	('ม่วง','green',0),	('ม่วง','purple',0),	('ม่วง','yellow',0),
('เหลือง','black',0),	('เหลือง','blue',0),	('เหลือง','red',0),	('เหลือง','green',0),	('เหลือง','purple',0),	('เหลือง','yellow',0);

INSERT INTO change_blindness_question 
(path_of_pic1, path_of_pic2, answer_area_width, answer_area_height, position_of_change_x, position_of_change_y) VALUES 
('/assets/images/02a.jpg', '/assets/images/02b.jpg', 20.0, 15.0, 25.0, 45.0),
('/assets/images/04a.jpg', '/assets/images/04b.jpg', 25.0, 45.0, 7.0, 40.0),
('/assets/images/01a.jpg', '/assets/images/01b.jpg', 10.0, 10.0, 46.0, 43.0),
('/assets/images/06a.jpg', '/assets/images/06b.jpg', 5.0, 13.0, 70.0, 57.0),
('/assets/images/07a.jpg', '/assets/images/07b.jpg', 5.0, 8.0, 75.0, 39.0),
('/assets/images/03a.jpg', '/assets/images/03b.jpg', 17.0, 10.0, 35.0, 52.0);
